import { useState } from 'react';
import PaymentButtons from './PaymentButtons';
import './Pricing.css';

export default function Pricing() {
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'annual'>('monthly');

    const plans = [
        {
              id: 'start',
                    name: 'Старт',
                          desc: 'Для небольших проектов и быстрого старта',
                                priceMonthly: '$29',
                                      priceAnnual: '$24',
                                            features: [
                                                    'До 1 000 диалогов / мес',
                                                            'Интеграция с Telegram и Viber',
                                                                    'Базовая аналитика',
                                                                            'Поддержка 24/7',
                                                                                  ],
                                                                                        popular: false,
                                                                                            },
                                                                                                {
                                                                                                      id: 'pro',
                                                                                                            name: 'Про',
                                                                                                                  desc: 'Для растущего бизнеса со множеством каналов',
                                                                                                                        priceMonthly: '$79',
                                                                                                                              priceAnnual: '$65',
                                                                                                                                    features: [
                                                                                                                                            'До 10 000 диалогов / мес',
                                                                                                                                                    'Все интеграции (Telegram, Viber, Instagram)',
                                                                                                                                                            'Расширенная аналитика и CRM',
                                                                                                                                                                    'Приоритетная поддержка',
                                                                                                                                                                            'Кастомные сценарии',
                                                                                                                                                                                  ],
                                                                                                                                                                                        popular: true,
                                                                                                                                                                                            },
                                                                                                                                                                                                {
                                                                                                                                                                                                      id: 'business',
                                                                                                                                                                                                            name: 'Бизнес',
                                                                                                                                                                                                                  desc: 'Индивидуальные решения под ваши задачи',
                                                                                                                                                                                                                        priceMonthly: '$199',
                                                                                                                                                                                                                              priceAnnual: '$159',
                                                                                                                                                                                                                                    features: [
                                                                                                                                                                                                                                            'Безлимитные диалоги',
                                                                                                                                                                                                                                                    'Персональный менеджер',
                                                                                                                                                                                                                                                            'Индивидуальные интеграции',
                                                                                                                                                                                                                                                                    'SLA 99.9%',
                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                popular: false,
                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                      ];

                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                            <section className="pricing" id="pricing">
                                                                                                                                                                                                                                                                                                  <div className="pricing__container">
                                                                                                                                                                                                                                                                                                          <h2 className="pricing__title">Тарифные планы</h2>
                                                                                                                                                                                                                                                                                                                  <p className="pricing__subtitle">
                                                                                                                                                                                                                                                                                                                            Выберите подходящий тариф для автоматизации вашего бизнеса
                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                            <div className="pricing__toggle-wrapper">
                                                                                                                                                                                                                                                                                                                                                      <span className={`pricing__toggle-label ${billingCycle === 'monthly' ? 'active' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                  Ежемесячно
                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                  className={`pricing__toggle-btn ${billingCycle === 'annual' ? 'active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setBillingCycle(billingCycle === 'monthly' ? 'annual' : 'monthly')}
                                                                                                                                                                                                                                                                                                                                                                                                                          aria-label="Переключить период оплаты"
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="pricing__toggle-slider"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={`pricing__toggle-label ${billingCycle === 'annual' ? 'active' : ''}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ежегодно <span className="pricing__discount">-20%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="pricing__grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {plans.map((plan) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const price = billingCycle === 'annual' ? plan.priceAnnual : plan.priceMonthly;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={plan.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`pricing-card ${plan.popular ? 'pricing-card--popular' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {plan.popular && <div className="pricing-card__badge">Популярный</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="pricing-card__title">{plan.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="pricing-card__desc">{plan.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="pricing-card__price">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="pricing-card__amount">{price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="pricing-card__period">/ месяц</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ul className="pricing-card__features">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {plan.features.map((feature, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <li key={idx} className="pricing-card__feature">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ✓ {feature}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <PaymentButtons planName={plan.name} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
