import React, { useState } from 'react';
import PaymentButtons from './PaymentButtons';
import './Pricing.css';

export default function Pricing() {
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'yearly'>('monthly');

    const plans = [
        {
              id: 'start',
                    name: 'Старт',
                          desc: 'Ідеально для знайомства з AI',
                                priceMonthly: 19,
                                      priceYearly: 15,
                                            features: [
                                                    '1 AI-чат-бот',
                                                            'До 1,000 відповідей / міс',
                                                                    'Базовая интеграция',
                                                                            'Email підтримка',
                                                                                  ],
                                                                                        popular: false,
                                                                                            },
                                                                                                {
                                                                                                      id: 'pro',
                                                                                                            name: 'Про',
                                                                                                                  desc: 'Для зростаючого бізнесу',
                                                                                                                        priceMonthly: 49,
                                                                                                                              priceYearly: 39,
                                                                                                                                    features: [
                                                                                                                                            'До 3 AI-чат-ботів',
                                                                                                                                                    'До 10,000 відповідей / міс',
                                                                                                                                                            'Пріоритетна підтримка',
                                                                                                                                                                    'Інтеграція з CRM',
                                                                                                                                                                            'Кастомне навчання бота',
                                                                                                                                                                                  ],
                                                                                                                                                                                        popular: true,
                                                                                                                                                                                            },
                                                                                                                                                                                                {
                                                                                                                                                                                                      id: 'business',
                                                                                                                                                                                                            name: 'Бізнес',
                                                                                                                                                                                                                  desc: 'Максимальна потужність',
                                                                                                                                                                                                                        priceMonthly: 99,
                                                                                                                                                                                                                              priceYearly: 79,
                                                                                                                                                                                                                                    features: [
                                                                                                                                                                                                                                            'Необмежено ботів',
                                                                                                                                                                                                                                                    'Безлімітні відповіді',
                                                                                                                                                                                                                                                            'Персональний менеджер',
                                                                                                                                                                                                                                                                    'VIP інтеграція под ключ',
                                                                                                                                                                                                                                                                            'SLA 99.9%',
                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                        popular: false,
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                              ];

                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                    <section id="pricing" className="pricing section">
                                                                                                                                                                                                                                                                                                          <div className="container">
                                                                                                                                                                                                                                                                                                                  <div className="pricing__header">
                                                                                                                                                                                                                                                                                                                            <h2 className="section-title">Тарифні плани</h2>
                                                                                                                                                                                                                                                                                                                                      <p className="section-subtitle">Оберіть рішення, яке найкраще відповідає масштабам вашого бізнесу</p>
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                          <div className="pricing__toggle-container">
                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                    className={`pricing__toggle-btn ${billingCycle === 'monthly' ? 'pricing__toggle-btn--active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setBillingCycle('monthly')}
                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                            Щомісяця
                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`pricing__toggle-btn ${billingCycle === 'yearly' ? 'pricing__toggle-btn--active' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setBillingCycle('yearly')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Щорічно <span className="pricing__discount">-20%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="pricing__grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {plans.map((plan) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const price = billingCycle === 'yearly' ? plan.priceYearly : plan.priceMonthly;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={plan.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`pricing-card ${plan.popular ? 'pricing-card--popular' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {plan.popular && <div className="pricing-card__badge">Популярний</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="pricing-card__title">{plan.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="pricing-card__desc">{plan.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="pricing-card__price">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="pricing-card__amount">${price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="pricing-card__period">/ місяць</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="pricing-card__features">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {plan.features.map((feature, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={idx} className="pricing-card__feature-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ✓ {feature}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <PaymentButtons planId={plan.id} planName={plan.name} price={price} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
